# nixpacks.toml

[phases.setup]
# Lista de paquetes del sistema (dependencias) que Chrome necesita para correr.
aptPkgs = [
    "libgconf-2-4",
    "libgdk-pixbuf2.0-0",
    "libgtk-3-0",
    "libnss3",
    "libxss1",
    "libasound2",
    "libxtst6",
    "libx11-xcb1",
    "libglib2.0-0"
]

[start]
# Comando para iniciar tu aplicación.
command = "python screenshot_script.py"